## 4-е домашнее задание - Библиотека numpy
# Филиппова А.Д. НПМбд-01-20
Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [30]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2. Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....


In [31]:
n=int(input("Введите n:"))
np.array([1, 2, 3] * n)

Введите n:4


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [32]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [33]:
matrix = np.zeros((10,10))
matrix[ : : 9] = 1
matrix[ : , [0,9]] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [34]:
matrix = np.zeros((8,8))
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [36]:
def matrix_create(n):
    matrix1 = np.ones((n, n)) * np.linspace(0, n - 1, n)
    matrix2 = matrix1.T
    return matrix1 + matrix2
n=int(input("Введите n:"))
matrix_create(n)

Введите n:8


array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [40]:
vector1 = np.random.randint(10, size=(1, 6))
vector2 = vector1.T
matrix = np.random.randint(10, size=(6, 6))
print("Умножение вектора на вектор =", np.dot(vector1, vector2))   
print("Умножение матрицы на вектор =\n", np.dot(matrix, vector2))   
print("Умножение матрицы на матрицу =\n",np.dot(matrix, matrix))   

Умножение вектора на вектор = [[116]]
Умножение матрицы на вектор =
 [[ 86]
 [133]
 [130]
 [116]
 [ 90]
 [ 69]]
Умножение матрицы на матрицу =
 [[123  41  86 142 153 183]
 [136  76 114 132 157 197]
 [ 77  67  95 110 101 142]
 [114  68 104 121 144 174]
 [ 79  59  67  69 104 128]
 [ 69  36  51  88  81 105]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [44]:
cos = np.cos(np.arange(0, 1.001, 0.05))
print("cos =\n", cos)
sin = np.sin(np.arange(0, 1.001, 0.05))
print("sin =\n", sin)
print(np.hstack((cos,sin)))

cos =
 [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231]
sin =
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
 0.78332691 0.8134155  0.84147098]
[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231 0.         0.04997917 0.09983342
 0.14943813 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834
 0.43496553 0.47942554 0.52268723 0.56464247 0.60518641 0.64421769
 0.68163876 0.71735609 0.75128041 0.78332691 0.8134155  0.84147098]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [54]:
A = np.random.rand(3, 5) * 4 - 1
A

array([[ 0.35390248,  2.4261762 ,  2.35125867,  2.60536786,  2.39819669],
       [ 0.33198602,  0.29128397,  0.90737338,  0.01593054,  1.68443347],
       [ 0.21143699, -0.76470825,  0.03910394,  1.98553433,  2.93218359]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [55]:
sum_all = A.sum()
print("Сумма по всем элементам", sum_all)
sum_string = A.sum(1) 
print("Сумма по строкам", sum_string)
sum_colomn = A.sum(0) 
print("Сумма по столбцам", sum_colomn)
mean = A.mean(1)
print("Среднее значение", mean)
dispers = A.var(1)
print("Дисперсия", dispers)
stand_dev = A.std(1)
print("Стандартное отклонение", stand_dev)

Сумма по всем элементам 17.76945987090524
Сумма по строкам [10.13490189  3.23100738  4.4035506 ]
Сумма по столбцам [0.89732549 1.95275191 3.29773599 4.60683273 7.01481376]
Среднее значение [2.02698038 0.64620148 0.88071012]
Дисперсия [0.7072074  0.35361514 1.85856181]
Стандартное отклонение [0.84095624 0.59465548 1.3632908 ]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [56]:
A = ((A.T - mean) / stand_dev).T
A

array([[-1.9894946 ,  0.47469273,  0.38560662,  0.68777357,  0.44142168],
       [-0.52839916, -0.5968456 ,  0.43919868, -1.05989259,  1.74593867],
       [-0.4909247 , -1.206946  , -0.61733431,  0.81040979,  1.50479521]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [57]:
third_colomn = A[:: , 2]
index_sort = np.argsort(third_colomn)
A = A[index_sort]
print("Отсортированная по 3-ему столбцу А\n", A)

Отсортированная по 3-ему столбцу А
 [[-0.4909247  -1.206946   -0.61733431  0.81040979  1.50479521]
 [-1.9894946   0.47469273  0.38560662  0.68777357  0.44142168]
 [-0.52839916 -0.5968456   0.43919868 -1.05989259  1.74593867]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [60]:
Trans_A = A.T
print("AT=\n", Trans_A)
B = np.dot(Trans_A, A)
print("B=\n", B)
С = np.dot(A, Trans_A)
print("C=\n", С)

AT=
 [[-0.4909247  -1.9894946  -0.52839916]
 [-1.206946    0.47469273 -0.5968456 ]
 [-0.61733431  0.38560662  0.43919868]
 [ 0.81040979  0.68777357 -1.05989259]
 [ 1.50479521  0.44142168  1.74593867]]
B=
 [[ 4.4783015  -0.03650632 -0.69616984 -1.20612563 -2.53949972]
 [-0.03650632  2.0382765   0.66600002 -0.0190475  -2.64872271]
 [-0.69616984  0.66600002  0.72268959 -0.70058716  0.00806738]
 [-1.20612563 -0.0190475  -0.70058716  2.25316883 -0.32740854]
 [-2.53949972 -2.64872271  0.00806738 -0.32740854  5.50756358]]
C=
 [[5.         1.38734301 2.47696502]
 [1.38734301 5.         0.97901599]
 [2.47696502 0.97901599 5.        ]]


### Матрица B размером 5 на 5, матрица С размером 3 на 3.  Отличие этих матриц в значениях, которые в них хранятся, а также в количестве значений (в В 25 , в С 9), сходство в типе данных (float) , который они хранят.

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [62]:
sum_diagB = np.trace(B)
sum_diagC = np.trace(С)
sum_all = sum_diagB + sum_diagC
print("Сумма диагональных элементов B и C =", sum_all)

Сумма диагональных элементов B и C = 30.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [270]:
#detA =np.linalg.det(A) 
print("Не можем посчитать, так как матрица А не является квадратной матрицей")
#print("Определитель A", detA)
detB = np.linalg.det(B) 
print("Определитель B", detB)
detC =np.linalg.det(С) 
print("Определитель C", detC)
rangA = np.linalg.matrix_rank(A)
print("Ранг A", rangA)
rangB = np.linalg.matrix_rank(B)
print("Ранг B", rangB)
rangС = np.linalg.matrix_rank(С)
print("Ранг С", rangС)
spektrB = np.linalg.eigvals(B)
print("Спектр B", spektrB)
spektrC = np.linalg.eigvals(С)
print("Спектр C", spektrC)


Не можем посчитать, так как матрица А не является квадратной матрицей
Определитель B -2.447556542865467e-31
Определитель C 39.78922098932378
Ранг A 3
Ранг B 3
Ранг С 3
Спектр B [ 1.02705801e+01  3.67534197e+00  1.05407790e+00 -3.18464207e-16
 -1.00093058e-15]
Спектр C [10.27058013  1.0540779   3.67534197]


### У матриц A, B и С одинаковый ранг, а длины спектров соотносятся с размерностями матриц.

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [271]:
np.random.seed(1032201729)
np.random.randint(0,8, size=1)

array([4])

In [69]:
right_answer_4 = 0.785398
right_answer_9 = 1.11072073454

In [70]:
print("Аналитическое решение для 4-ого интеграла = " , right_answer_4)
print("Аналитическое решение для 9-ого интеграла = " , right_answer_9)

Аналитическое решение для 4-ого интеграла =  0.785398
Аналитическое решение для 9-ого интеграла =  1.11072073454


In [73]:
def f(x):
    return 1 / (x * (1 + (np.log(x)) ** 2))
variant = 4
eps = 0.00001
right_answer = 0.785398
lower_bound = 1
upper_bound = np.e
print(get_rectangle_answer())
print(get_trapezoidal_answer())
print(get_simpson_answer())

Численное решение для интеграла 4 методом прямоугольников = 0.785405586172153, количество итерации = 5
Численное решение для интеграла 4 методом трапеции = 0.7854015066868394, количество итерации = 4
Численное решение для интеграла 4 методом Симпсона = 0.7853953744576965, количество итерации = 4


In [74]:
def f(x):
    return 1 / ((2 + 3 * x - 2 * (x ** 2)) ** (1 / 2))
variant = 9
eps = 0.001
right_answer = 1.11072073454
lower_bound = 3/4
upper_bound = 2
print(get_rectangle_answer())
print(get_trapezoidal_answer())
print(get_simpson_answer())

Численное решение для интеграла 9 методом прямоугольников = 1.1100679479383213, количество итерации = 6
Численное решение для интеграла 9 методом трапеции = 1.1098440542343122, количество итерации = 6
Численное решение для интеграла 9 методом Симпсона = 1.110400436291967, количество итерации = 7


In [71]:
def rectangle_method(delta_x, x):
    return delta_x * np.sum(f(x))
def trapezoidal_method(delta_x, x):
    return delta_x / 2 * ((f(x[0]) + 2 * np.sum(f(x[1:-1])) + f(x[-1]))) 
def simpson_method(delta_x, x):
    return delta_x / 3 * ((f(x[0]) + 2 * np.sum(f(x[2:-1:2])) + 4 * np.sum(f(x[1:-1:2])) + f(x[-1]))) 

In [72]:
def get_rectangle_answer():
    step = 1
    result_rectangle_method = 10
    N = 0
    while abs(right_answer - result_rectangle_method) > eps:
        step /= 10
        array_x = np.arange(lower_bound, upper_bound, step)
        if variant != 9:
            array_x = np.append(array_x, upper_bound)
        result_rectangle_method = rectangle_method(step, array_x)
        N += 1
    return "Численное решение для интеграла " + str(variant) + " методом прямоугольников = " + str(result_rectangle_method) + ", количество итерации = " + str(N)

def get_trapezoidal_answer():
    step = 1
    result_trapezoidal_method = 10
    N = 0
    while abs(right_answer - result_trapezoidal_method) > eps:
        step /= 10
        array_x = np.arange(lower_bound, upper_bound, step)
        if variant != 9:
            array_x = np.append(array_x, upper_bound)
        result_trapezoidal_method = trapezoidal_method(step, array_x)
        N += 1
    return "Численное решение для интеграла " + str(variant) + " методом трапеции = " + str(result_trapezoidal_method) + ", количество итерации = " + str(N)

def get_simpson_answer():
    step = 1
    result_simpson_method = 10
    N = 0
    while abs(right_answer - result_simpson_method) > eps:
        step /= 10
        array_x = np.arange(lower_bound, upper_bound, step)
        if variant != 9:
            array_x = np.append(array_x, upper_bound)
        result_simpson_method = simpson_method(step, array_x)
        N += 1
    return "Численное решение для интеграла " + str(variant) + " методом Симпсона = " + str(result_simpson_method) + ", количество итерации = " + str(N)

### При увеличении числа шагов разница между аналитическим и численным решением уменьшается, то есть повышается точность
